import api from './api';
export const getRoutes = (params) => api.get('/routes', { params });
export const getRoute = (code) => api.get(`/routes/${code}`);
export const createRoute = (data) => api.post('/routes', data);
export const updateRoute = (code, data) => api.put(`/routes/${code}`, data);
export const updateRouteStatus = (code, status) => api.patch(`/routes/${code}/status`, { status });
export const getRouteDirections = (code) => api.get(`/routes/${code}/directions`);
export const createRouteDirection = (code, data) => api.post(`/routes/${code}/directions`, data);
export const updateRouteDirection = (code, directionId, data) => api.put(`/routes/${code}/directions/${directionId}`, data);
export const deleteRoute = (code) => api.delete(`/routes/${code}`);
export const generateSchedule = (code) => api.post(`/routes/${code}/generate-schedule`);
